### ISSUE TITLE
Flytte over Delegerings-tester for Cypress til Playwright

### ISSUE THREAD

**Issue by Nyeng** [Altinn/altinn-access-management-frontend#1023]
### Description

@acn-Sneha har gjort en god innsats med å flytte over en del tester allerede, her kommer oppgaven for resten av testene som skal flyttes

### Tasks

 - [x] Delegate api to an organization and verify it in his Delegations overview page and delete APIs delegated
 - [x] Delegate api to an organization and supplierOrg verifies it in its Delegations overview page and delete APIs it received
 - [x] Delegate api to organization to which api was delegated before
 - [x] Verify filtering of API providers in API delagation and verify Forrige/ Neste buttons
 - [x] Delegate api to an organization by selecting from API providers filter
 - [x] Verify adding multiple organizations and APIs and deleting them
 - [x] Delegate multiple APIs to multiple orgs and verify them
 - [x] Verify Tilgangstyrer do not have access to API delegering panel
 - [x] Verify user with Programmeringsgrensesnitt (API) role have access to API delegering panel
 - [x] Verify when user does not have access to delegate an API

### Acceptance Criterias

Gitt at jeg ønsker bedre testdekning i Playwright
Og bli kvitt teknisk gjeld fra gamle tester
Når jeg flytter over eksisterende Cypress-test og skriver om til Playwright
Så sparer vi oss for teknisk gjeld og forbedrer testdekningen til nåværende ende til ende-tester
