### ISSUE TITLE
Fikse bedre rapportering for Playwright I Pipeline + andre forbedringer

### ISSUE THREAD

**Issue by Nyeng** [Altinn/altinn-access-management-frontend#1076]
# Beskrivelse

```[tasklist]
### Tasks
- [ ] Publisere lesbare testresultater med skjermbilde som illustrerer bedre hvorfor en test feiler
- [ ] Legg til deploy mot AT21 og AT22 igjen (ble fjernet ved et uhell tror jeg) 
- [ ] Juster på timeout for testene slik at de ikke kjører i nesten 30 minutter dersom alle testene feiler
- [ ] Vurder å legge til retry-steg via config for å minimere flakyness. 
```

#### Annet
- Fjern ".pause()"-stegene som ikke burde sjekkes inn i Playwright

# To do's

- [ ] Eks: Ta ut av oppvaskmaskinen

**Comment by Nyeng** [comment]
Dropper timeout-steget... vet ikke helt hva jeg skal sette det til, og krevende å teste uten at noe faktisk feiler i Pipeline.
