### ISSUE TITLE
Automate resource deployments for CDN i Azure

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#124]
### Description

Until we decide on backend for frontend, we will host the built front end assets and entry javascript in a blob storage as static website. Have we decided on altinn CDN?

### Tasks
Create scripts
- [ ]  to establish a storage account, blob storage and set it as static website
- [ ] Trigger build and copy from frontend repo to the specified blob storage/CDN repository after every commit to the main branch in front end repository

### Acceptance Criterias
- [ ] Commits to frontend main branch must be built and copied to the cdn repo or blob storage

**Comment by sivaglen** [comment]
Kan denne lukkes nå som du lager BFF @acn-dgopa

**Comment by acn-dgopa** [comment]
@sivaglen stemmer. lukker saken
