### ISSUE TITLE
Build and deploy script for BFF

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#162]
### Description

We will be using Azure container apps for  access management BFF with frontend. Deployment will be triggered when code is merged into main branch. Github action will be triggered and code is built and packed into a container registry and deployed to azure container apps.

### Additional Information

- Frontend must be built as a stage in the same docker file
- caching must be implemented to speed up the build and deploy process

### Tasks

- [x] Build and deploy action for BFF
- [x] Build step for backend
- [x] Build step for frontend
- [x] Deploy step to deploy to container app
- [x] Environment variables are created along with the container app (should be part of provisioning)

### Acceptance Criteria

- [x] Application is deployed to azure container app
