### ISSUE TITLE
Update frontend  for bff

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#174]
### Description

Frontend is currently connecting directly to the accessmanagement api. The accessmanagement component serves both internal and external api requests. 
Language, resource information mapping logic is implemented in frontend which is difficult to maintain in the frontend in long run. These logic are now moved to bff application and a simple data structure is exposed to frontend.
Also vite build generates entrypoint-xxxx.js as filename but this changes with every build. So we need to configure vite build such that f.ex entrypoint.js is genrated as filename.

we need to add something like

export default defineConfig({
  ...
  build: {
    rollupOptions: {
      output: {
        entryFileNames: `assets/[name].js`,
        chunkFileNames: `assets/[name].js`,
        assetFileNames: `assets/[name].[ext]`
      }
    }
  }
})

### Tasks

- [x] Update api endpoints to connect bff api
- [x] Update url to localization
- [x]  Update mapping based on new data structure
- [x] Setup entryfilename in vite build configuration

### Acceptance Criteria

- [ ] Access management UI loads
- [ ] Possible to view offered delegations
- [ ] Possible to view received delegations
- [ ] Possible to create new delegation

**Comment by sivaglen** [comment]
@Albertlarsen - er denne utført og venter på review? 
Evt hvem utfører review?

**Comment by Albertlarsen** [comment]
@sivaglen Tror egentlig denne er verifisert ved at ting faktisk fungerer i AT så vi kan lukke den.
