### ISSUE TITLE
Add more test coverage for bff and configure application insights

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#198]
### Description
We do not have enough test coverage for the bff api yet. we need to add more tests to cover all endpoints.
We need application insights to trace logs. 

### Tasks

- [ ] Add tests for those controllers that do not have test coverage
- [ ] Verify that sonar cloud is able to discover the tests and code coverage is calculated on PR run
- [ ] Add configuration for application insights

### Acceptance Criteria

- [ ] Application insights is setup
- [ ] unit tests are added for all endpoints
