### ISSUE TITLE
Documentation and create relevant issues for establishing a new environment for accessmanagement ui

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#199]
### Description
We need to update the documentation for localtest, infrastructure that is required to deploy to container app, security considerations, certificates, etc.
Issues relevant to these has to be created asap

### Tasks

- [x] Update localtest documentation
- [x] Create documentation for container deploy for accessmanagement ui
- [x] Create relevant issues for establishing a new environment for container apps

### Acceptance Criteria

- [x] Issues created
- [x] Localtest documentation updated
- [x] Deploy documentation created
