### ISSUE TITLE
API-delegering | S2b - OrgApiDelegationOverviewPage | Part 1

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#20]
### Description

Finish frontend for the view below:
![image.png](https://images.zenhubusercontent.com/62f9fa065864a52ea3938f4f/c8da8b0c-033b-4cc5-bf5d-31694eac9d53)

### Tasks

- [x] Localize all words
- [x] Create redux reducers
- [x] create redux reducer softAdd
- [x] create redux reducer softDelete
- [x] Start using DS components
- [x] Create redux reducer softAddAll
- [x] Create redux reducer softDeleteAll
- [x] Create mapper and dto for softDeletedItems
- [x] Make save button disabled state
- [x] Make toggle button state
- [x] Position components
- [x] Change to svg icon buttons instead of string buttons
- [x] Make edit state
- [x] Make edit reducer
- [x] Fix undo button pushing other components aside
- [x] Make buttons do what they should
- [x] Setup redux toolkit with cypress
- [x] Write tests for main functionality
- [x] Make code for edit state edge cases
- [x] Write tests for edit state

### Acceptance Criterias
- [ ] "Rediger tilganger"-button should enable edit possibilities
- [ ] "Slett"-button should soft delete
- [ ] "Lagre"-button should delete for real
- [ ] "Deleger API til ny bedrift"-button should take you to view S4
- [ ] "Gi API"-button should take you to view 
- [ ] All organisations with connection to your apis should be listed
- [ ] 'Deleger-nytt-api'-button should take you to view
