### ISSUE TITLE
Støtte for loading på Button i Digdir Designsystem

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#202]
### Description

Dette er en kopi av det egentlige issuet i Designsystemets backlog: https://github.com/digdir/designsystem/issues/204
Det omhandler tilrettelegging for visning av loading i button samt endringer for økt tilgjengelighet.

### Description

We should give the user immediate feedback when they hit a button and waiting for something to happen.

n cases where the content takes some time to load, we should add a spinning icon next to the text inside the button, that disappear once the content appears.  Something like this: 

![image](https://user-images.githubusercontent.com/1464915/222104760-6a41ea46-83fa-457a-bcc5-54e2b5254358.png)

### Tasks:
- [x] Use existing spinner component in Storybook example
- [x] Added support for aria-disabled (Using disabled on Button are not readable by assistive technologies such as screen readers so they will not "see" that there is something loading that the have to wait for)
- [x] Set title prop on Spinner to be optional as the button will cover this
- [ ] Get the code through DS QA
