### ISSUE TITLE
Provisioning infrastructure for AccessManagement UI

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#212]
### Description

AccessManagement UI applicaiton is running on an Azure Container app. To establish a new environment, we need the following infrastructure

- Github registry (No special automation script is required for this, It is integrated into build and publish script)
- Provisioning Azure Resources for container app
    - Resource group specific to accessmanagement ui
    - Azure Active Directory app to establish integration between github and container app for deployment.
        - Github action will use the credentials from AD app to login to azure (OpenId Connect)
    - Container apps environment
    - Container app
        - Environment variables for the container app - Values.yml file to maintain environmenrt specific values
    - Keyvault 
### Tasks

- [x] Provisioning script to establish a new environment for accessmanagement ui container app
- [x] Enable managed identity in container app for keyvault ing
- [x] Values.yml file to be created for each environment
- [x] Certificate for accesstoken for all environments
- [x] Certficate is stored in keyvault for different environments
- [x] Platform subscription key (for api management) for all environments

### Acceptance Criteria

- [x] Provisioned Infrastructure for environments for at21, at22, at23, at24
- [x] Provisioned Infrastructure for environment yt01
- [x] Provisioned Infrastructure for environments for tt02
- [x] Provisioned Infrastructure for environments for prod
- [x] Verify at deploy script is able to deploy to the established environments

**Comment by acn-dgopa** [comment]
Release and deploy will be followed up in #214

**Comment by sivaglen** [comment]
@acn-dgopa - er dette nødvendig for å gå i produksjon med migrering av DelegationScheme?

**Comment by acn-dgopa** [comment]
> @acn-dgopa - er dette nødvendig for å gå i produksjon med migrering av DelegationScheme?

@sivaglen Ja, @simon-ellefsen  jobber med saken
