### ISSUE TITLE
Deploy and release plan for accessmanagement ui

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#214]
### Description

We have a github action to build, package, publish to github registry and then deploy to container app from registry. We need to come up with an advanced script to deploy to different testing environments (AT21, AT22, AT23, AT24). We also need a routine to deploy to tt02 and production.

### Release Process
We will build and deploy to the AT environments whenever a pull request is merged into main branch. 

1. Code is built 
2. Package is created in github container registry with the commit sha as tag for the image. F.ex altinn/altinn-access-management-frontend: {commitsha}
3. A release is drafted/updated
4. The package is then deployed to specific AT environments.
5. When we are ready for deployment in TT02/Production and we decide to create a release on/until a specific commit, we create a git tag for the commit sha, get the package at the specific commit sha and add the version tag. F.ex create a tag v1.0.0 at commit "8302b0f" and add the same tag to the image with the commit sha. This can be acheived by running the workflow
6. Deploy the release version to TT02/prod
7. Publish the release manually by going into the draft and clicking publish

### Tasks

- [x] Create AT, TT and prod environments in github
- [x] Update or create script to deploy to different environments
- [x] Automatic deploy to at environments
- [x] Add reviewer to enable deploy to tt02
- [x] Add reviewer to enable deploy to production

### Acceptance Criteria

- [ ] Deploy actions are created to deploy to different environments
- [ ] Deploy to tt02 is enabled only by a reviewer
- [ ] Deploy to production is enabled only by a reviewer
- [ ] Release plan is created
