### ISSUE TITLE
Implement accesstoken generation

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#266]
### Description
We need accesstoken to connect to different platform components. To generate access token we need a certificate. The certificate must be stored in the keyvault.
We use the accesstoken package to generate token. Currently the signingcredentialresolver does not support keyvault access to get certificate information. So we need to fetch the certificate from keyvault and generate token with a certificate
### Tasks

- [x] Certificate to generate access token
- [x] Access token provider to retreive certificate from keyvault and generate token based on that

### Acceptance Criteria

- [x] Certificate is created for accesstoken generation
- [x] Accesstoken is generated
- [x] Able to integrate with platform component

**Comment by jonkjetiloye** [comment]
Old resolved and verified infrastructure change. Closing issue
