### ISSUE TITLE
Update profile api endpoint to fetch userprofile from profile component instead of accessmanagment

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#267]
### Description
Currently Bff fetches user profile information from the accessmanagement component. This must be routed to profile component. 

### Tasks

- [ ] Update profileclient to route to profile component
- [ ] Create profileservice
- [ ] Create profilehelper to getlanguagecode
- [ ] Create authenticationhelper to get user id from context
- [ ] Refactor language cookie setting
- [ ] Add subscriptionkey to profile endpoint
- [ ] Add certificate for accesstoken generation

### Acceptance Criteria

- [ ] Profile endpoint fetches user profile from profile component
- [ ] Languagecookie is set
- [ ] Languagecode is fetched based on user preferences

**Comment by jonkjetiloye** [comment]
Technical implementation change which has been verified and old implementation of user profile retrieval in accessmanagement has been removed. Closing issue
