### ISSUE TITLE
Fix Sonarcloud analyzer

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#268]
### Description
Sonarcloud scanner fails

### Tasks

- [ ] Troubleshoot and find the underlying issue

### Acceptance Criteria

- [ ] Sonarcloud analyzer runs
- [ ] Analysis result is published

**Comment by jonkjetiloye** [comment]
Ref.: https://docs.sonarcloud.io/advanced-setup/automatic-analysis/#conflict-with-ci-based-analysis
it's caused by the sonarcloud project being configured for automatic analysis. Will get admin of project to update.
