### ISSUE TITLE
Help infrastructure provisioning and test deploymnet

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#293]
### Description

@simon-ellefsen is setting up script to provision infrastructure for hosting access management frontend app in Azure container app. Assist him with the setup process.
Test deployment to different environments

### Tasks

- [x] Test deployment to AT21
- [x] Test application in AT21

### Acceptance Criteria

- [ ] Regression tests passed

**Comment by acn-dgopa** [comment]
AT21 deployment succeeded but still domain setup is not in place yet for testing the actual application

**Comment by acn-dgopa** [comment]
AT21 is available as a complete environment for testing @rtafj @anishastphen @jonkjetiloye @annerisbakk @allinox @Albertlarsen
