### ISSUE TITLE
Setup Configuration for automatic labeling for PR's

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#294]
### Description

We have github action to automatically draft release notes when a new release is created. To support that, we need to label the PR with type of change that is added to the application. To avoid manual labelling or enforcing labelling, it is possible to add automatic labelling to PR based on branch, file name.

### Tasks

- [ ]  Discuss with the team and agree on the branch structure
- [ ] Add configuration for automatic PR labelling

### Acceptance Criteria

- [ ] Labels are added automatically to PR
