### ISSUE TITLE
Setup secret values to be loaded into configuration

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#299]
### Description

The environment variables were expected to be setup as part of terraform script which was run from Azure pipelines. But then we will have to maintain the variable for each environment in another repository. We might end up duplicating in multiple places. 
To avoid that, we will add all environment variables as part of github repository. Each environment will have its appsettings file. Setting the ASPNETCORE_ENVIRONMENT fetches the environment specific appsettings file.  The appsettings is resolved in #298 
Any secret variable will be stored as secret in keyvault. Keyvault configuration must be added to solve it

### Tasks

- [x] Update program.cs to add secret values to configuration
- [x] Update the secret in keyvault (This should be done via terraform script )

### Acceptance Criteria

- [x] Secret is created in the keyvault
- [x] Application works as before

**Comment by jonkjetiloye** [comment]
Resolved infrastructure task. Closing the issue.
