### ISSUE TITLE
Move rest of the non-sensitive configuration values from environment variables to appsettings

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#308]
### Description

We still have some configuration created as environment variables in the container app. These are not secrets and can be moved to appsettings file like the other configuration values

### Tasks

- [x] Move cacheconfig, client settings, keyvaultsettings to appsettings
- [ ] Remove the environment variables from at21,at23

### Acceptance Criteria

- [ ] Configurations moved to appsettings
- [ ] Regression tests passed
