### ISSUE TITLE
Frontend changes are reflected only on clearing cache

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#320]
## Description of the bug

Frontend has some new changes. The changes are built and deployed to the testing environment but the changes are not reflected until we clear the cache.

## Steps to Reproduce

1. Make some visible changes in the UI. F.ex cahnge a colour of a button or update some text
2. Merge to main branch via PR
3. Wait for deploy
4. Test the application
5. Changes made in step 1 are not visible

## Cause

This is because the javascript/css file name is the same and the js/css filea are downloaded again on the client only when the js/css filenames are different. 

## Resolution

Update the cshtml to use the dynamic file names that is produced by vite.config

## Tasks

- [ ] Update vite.config to generate dynamic filenames as before
- [ ] Update dockerfile to copy these files into wwwroot
- [ ] update cshtml to load dynamic files

## Acceptance Criteria

- Frontend changes are reflected immediately without clearing cache
