### ISSUE TITLE
Setup deploy and test deploy in new AT environments

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management-frontend#336]
### Description

Extend the deploy script to deploy to all AT environments. Currently, it deploys to AT21, AT22.

### Tasks

- [x] Add environment variables and secrets to AT23, AT24
- [x] Update deploy script to deploy to AT23, AT24
- [x] Remove unused/outdated workflows

### Acceptance Criteria

- [x] Deploy script deploys to AT21, AT22, AT23, AT24

**Comment by jonkjetiloye** [comment]
Completed infrastructure task. Closing issue
