### ISSUE TITLE
Set security headers and coors

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management-frontend#347]
### Description

We need to set the recomended security headers in BFF 
See 
https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Api/Infrastructure/Middleware/SecurityHeadersMiddleware.cs

### Tasks

- [x] Set security headers
- [ ] Make sure corrs prevent XSRF

### Acceptance Criteria
- [x] Security headers are set
- [ ] Corrs possibility is disabled

**Comment by jonkjetiloye** [comment]
Verified response headers are now set:
`referer-policy: no-referer
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 0`

**Comment by sivaglen** [comment]
@jonkjetiloye - betyr det at denne kan lukkes?

**Comment by jonkjetiloye** [comment]
@sivaglen har da bare fått verifisert at security headers er satt.
@TheTechArch hvordan får vi ellers sjekket cors/XSRF?
