### ISSUE TITLE
API-delegering | Create responsive design

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#40]
### Description

Tasks

- [ ] Create mobile view for S2b | ApiDelegationOverviewPage | #41
- [x] Create mobile view for S3 | NewApiDelegationPage | #42
- [ ] Create mobile view for S4 | NewOrgDelegationPage | #43
- [ ] Create mobile view for S5a | ApiDelegationConfirmationPage | #44
- [ ] Create mobile view for S5b | ApiDelegationReceiptPage #45
