### ISSUE TITLE
API-delegering remaining small tasks

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#56]
### Tasks

 NewApiDelegationPage:
- [x] Display redux state chosen orgs in CompactDeletableListItems in NewApiDelegationPage
- [x] Localize all words
- [x] Fix margins between forrige/tilbake-buttons
- [x] Set height for div containing accordions to the same as  in NewOrgDelegationPage(think it's 300 px)
- [x] Disable "neste" button when redux state chosenDelegableApis is empty

Other:
- [x] Fix routing for all 'Forrige' and 'Neste'-buttons.
- [x] Add around 70 px to margin-bottom for navButtonContainers
- [x] Set background color on all Pages.
- [x] Set spacing and width on all Pages
- [x] Make "deleger nytt API"-button in overview take you directly to api-delegations/new-api page with redux state chosenDelegableOrgList prefilled
- [x] Reset redux states when returning to /api-delegations

See sketches: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=1209%3A8163&t=c5Lh5Vd6OpNXUx8Q-0

AC: 

- Every button does the expected behaviour
- Forrige button takes you to previous page
- Next button takes you to next page
- "deleger nytt API"-button with delegable orgs prefilled when clicked and you are taken to /new-org
- chosenDelegableOrgList and chosenDelegableApisList should be reset when returning to accessmanagement/ui/api-delegations
- You can search for API
- An API is removed from overview list when +-button is clicked and added to chosen API-list
- An API is removed from chosen APIs list when clicking on minus button on chosen APIs accordion list
- You can filter and search on API-names, the org of the API and the description of the API.
- API-lists is populated
