### ISSUE TITLE
API-delegering | S3 | NewApiDelegationsPage

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#67]
Make views in pictures at the bottom. Make the filter button and it's modal. See updated view in figma: https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=1209%3A8163

Frontend tasks ready:

- [x] Enable icon in DS TextField https://github.com/Altinn/altinn-design-system/issues/123
- [x] Make redux reducers needed to update lists
- [x] Part 1: NewApiDelegationsPage.
- [x] Create frontend search and filter functionality https://app.zenhub.com/workspaces/team-autorisasjon-og-formidling-62f4af5f4b1b711f056e6c46/issues/altinn/altinn-access-management-frontend/14
- [x] Finish last features NewApiDelegationsPage. | https://github.com/Altinn/altinn-access-management-frontend/issues/39

Blocked frontend tasks:
- [ ] hook up +button to do a backend call to check if the user has the right access level to delegate Altinn/altinn-access-management-frontend#66
- [ ] Populate data in accordions with getAlDelegableApis backend calll Altinn/altinn-access-management#204

AC:
- [ ] An API is removed from overview list when +-button is clicked and added to chosen API-list
- [ ] An API is removed from chosen APIs list when clicking on minus button on chosen APIs accordion list
- [ ] You can filter and search on API-names, the org of the API and the description of the API.

![image.png](https://images.zenhubusercontent.com/62f9fa065864a52ea3938f4f/6fc2aa95-128c-4ad5-9930-e45b760f8b07)
