### ISSUE TITLE
API-delegering | S2a 

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#68]
Make view in picture below. See figma for updated view: 

Ready frontend tasks:
- [x] Add functionality to have another button in Accordion https://github.com/Altinn/altinn-design-system/issues/128
- [x] Create S2a-accordion Altinn/altinn-access-management#143
- [ ] Create Ferdig/Lagre functionality Altinn/altinn-access-management-frontend#88

Frontend tasks on hold:
- [ ] Make sure buttons, sends user to the right places |  On hold until https://github.com/Altinn/altinn-design-system/issues/103 is finished
- [ ] Combine all DS components to create view | On hold until https://github.com/Altinn/altinn-design-system/issues/103 and  Altinn/altinn-access-management#56 is finished.

Backend tasks: 
- [ ] Altinn/altinn-access-management-frontend#92

![image](https://user-images.githubusercontent.com/31471142/191756391-2ca05ab2-7543-45f6-a35c-7a4896dbb2f7.png)
