### ISSUE TITLE
Create component Filter

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#81]
**Description:**
As a user, I would like to be able to filter data based on specific criteria within my application. It can be wise to see how other design systems has implemented a similar component. See picture for how it can be made.

**Tasks**

- [x] Go through and adjust the designs in Figma
- [x] Figure out a strategy for implementation
- [x] Implement an MVP
  - [x] Filter button opens popup
  - [x] Can close filter popup by clicking on filter button
  - [x] Clicking outside of popup closes it
  - [x] Popup contains checkboxes mapped by provided options list
  - [x] Selected checkboxes outputted from component when clicking 'Apply'
  - [x] When the list of options is long, the user can scroll through dem
  - [x] Apply button disabled when no changes have been made
  - [x] Options code list contains both values and labels
  - [x] All selected checkboxes unselected when clicking 'reset'
  - [x] Aria-expanded + aria-controls
  - [x] Filter button contains filter icon
  - [x] Pressing esc closes the popup
  - [x] Popup shifts along bottom when there is to little space to the right
- [x] Write tests for the MVP
- [x] Improve the MVP
  - [x] Mobile view with fullscreen modal instead of dropdown
  - [x] Can change options and values dynamically during runtime
  - [x] Search within the options
  - [x] Entire option is clickable?
  - [x] Styled to design using designsystem tokens
  - [x] Animation on opening of dropdown content
  - [x] Notification-circle that marks that there are active filters
- [x] Write tests for the full filter
- [x] Code cleanup

**Acceptance Criteria:**

- The filter component should allow users to apply multiple filters simultaneously.
- Users should be able to select different filter criteria such as date range, numeric range, and select from a list of options.
- The filter component should be made so it can be used on smaller mobile screens as well.
- The filter component should be accessible to users with disabilities, including support for keyboard-only navigation and screen readers.
- Should have elevation
- Change all places that uses old multiselect to use this new filter instead.

**Design review**
- Go to https://am.ui.at23.altinn.cloud/accessmanagement/ui/offered-api-delegations/choose-org and check the filter button.

![image](https://user-images.githubusercontent.com/22012997/232525485-8fa580e4-a896-4ab3-aa50-c2bec3c007c1.png)

**Comment by Randiabs** [comment]
sjekket, fungerer fint
