### ISSUE TITLE
Add Subscription key header on all accessmanagement backend API client integrations

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management-frontend#845]
### Description

Currently the BFF has been able to consume all the API endpoints from access management backend without a subscription key.

The BFF already have a subscription key used for access to other platform components: e.g. Profile and Register

Accessmanagement backend will also have to add subscription requirement, and as such a new subscription product will be created for the BFF, containing all the relevant APIs for the BFF. 

This mean that the existing Subscription key will need to be changed, as well as added to all current and future client implementations for calling any platform API using the header value: `Ocp-Apim-Subscription-Key`

### Tasks

- [ ] Update configured KeyVault value: `PlatformSettings--SubscriptionKey` to new subscription key
- [ ] Update ProfileClient to add Ocp-Apim-Subscription-Key header
- [ ] Update RegisterClient to add Ocp-Apim-Subscription-Key header
- [ ] Update MaskinportenSchemaClient to add Ocp-Apim-Subscription-Key header
- [ ] Update SingleRightsClient to add Ocp-Apim-Subscription-Key header

### Acceptance Criterias

Everything still works: 
- AccessManagement
-- API delegation
-- Single access delegation
- UserProfile
- Register

**Comment by Albertlarsen** [comment]
Blocked until the team has discussed it
