### ISSUE TITLE
Virksomhetens forespørsler/Company requests - Individual components - frontend

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management-frontend#85]
### Description

We need to create several components and styles to be able to create the feature in pic below. Links to each individual components can be found below:

- [x] Accordion: https://github.com/Altinn/altinn-design-system/issues/28
- [x] List: https://github.com/Altinn/altinn-design-system/issues/27
- [x] Dashed list style: https://github.com/Altinn/altinn-design-system/issues/78
- [x] Toggle button group: https://github.com/Altinn/altinn-design-system/issues/24
- [x] Popover - https://github.com/Altinn/altinn-design-system/issues/58
- [x] Fix Toggle Button bugs in design-system
- [x] Fix Accordion bug -  Altinn/altinn-access-management#44 
- [x] Accordion blue arrow style: https://github.com/Altinn/altinn-design-system/issues/91
- [ ] New behaviour for List component - https://github.com/Altinn/altinn-design-system/issues/119
- [ ] IconButton - On hold until studio has implemented quiet button. https://github.com/Altinn/altinn-design-system/issues/79
- [ ] Button variant action - On hold until Team Studio has implemented quiet button. https://github.com/Altinn/altinn-design-system/issues/26
- [ ]  LinkButton - On hold until UX has specified - UX has defined that link-buttons is not going to be used anymore - needs a redefinition. https://github.com/Altinn/altinn-design-system/issues/9

![image](https://user-images.githubusercontent.com/31471142/188402400-2fec0644-e770-42c7-814c-7dc8bd589bfa.png)
