### ISSUE TITLE
Develope helper methods for enkeltrettighetersdelegering functionality in playwright

### ISSUE THREAD

**Issue by acn-Sneha** [Altinn/altinn-access-management-frontend#898]
### **Description**
This issue created to develope helper methods in playwright for single right delegations functionality

### Tasks
- [x] Helper method for delegating resources to user 
- [x] Helper methos for delegating roles to SSN and Org
- [x] Helper method for adding different resources  
- [x] Helper method for verifying added resources shown under "Andre med rettigheter"
- [x] Helper method for verifying added resources shown under "Skjema og tjenester du har rettigheter til"
- [x] Helper method for verifying added resources shown under "Rettigheter du har hos andre"
