### ISSUE TITLE
Feilende e2e-tester skaper støy i release-prosessen

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management-frontend#960]
Pr nå lyser e2e-testene våre rødt, noe som skaper usikkerhet på om noe er galt eller ikke.

Fjern de testene som er flyttet over til playwright fra cypress og kjør playwright-testene på merge og release som hjelper for å få quick feedback, men hvis vi kjører testene etter hver PR da trenger vi å ha en script for å slette data fra database for å unngå så mye data i database som kan følge opp med knyttet task. 

```[tasklist]
### Tasks
- [x] Ta bort cypress testene som er flyttet til playwright
- [x] sette opp yml filen som skal kjøre testene etter hver push
- [x] Ta bort AT21 config filen fra kjøring av testene
- [x] Legge til TT02 testmiljø config file for å kjøre testene i tt02 miljø
- [x] Verifisere testene kjører grønn i alle AT(AT22, AT23 og AT24) som er stabil miljø
```

**Comment by acn-Sneha** [comment]
@allinox @Siri-Anna @rtafj Lukker tasken siden vi har kjøring av testene etter hver push i AT og TT02 som kjører grønn nå.
